### ISSUE TITLE
Cmake not rebuilding file after change - A way to fix it

### ISSUE THREAD

**Issue by PierreSanson** [CMM-22/a1#1]
Hello everyone,

During the exercise session, I encountered an issue where cmake would not rebuild the test correctly after I made a modification in some of the source code.
(I noticed because I had coded the solution for the first question, which I was pretty sure was correct, but the test would keep on failing.)

We solved the issue with the TAs during the session without fully understanding what was going on, but then I encountered the problem again at home.

However I found a solution: whenever you made changes, first select the app as your build target, build it, then select the test as your build target and build it. By doing this, it seems like everything is rebuilt properly.

I am not sure where the issue comes from, but hopefully this helps anyone who has the same issue.

**Comment by fdevinc** [comment]
Thanks for sharing your solution!
