### ISSUE TITLE
``auto`` keyword in Eigen – stay away!

### ISSUE THREAD

**Issue by lamyiowce** [CMM-22/a1#4]
Hey, this made me waste quite some time so I thought I'll just drop it here so fellow students don't experience the same problem. 
Using the ``auto`` keyword in Eigen may lead to incorrect results! Everything compiles, but the values are incorrect. More info here: https://stackoverflow.com/questions/36297425/explicit-type-declaration-vs-auto-in-eigen-expressions-in-c

**Comment by fdevinc** [comment]
This is a good point, avoid the `auto` keyword as much as you can with _Eigen_ :+1:
