### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by Bryanttt-tang** [CMM-22/a1#6]
Hi guys, I encountered Cmake error many times like shown in the image below and thus unable to build the file. Anyone know what's going on?
![c15768f7b1cb084e6269432b84ea8fc](https://user-images.githubusercontent.com/101058533/158485636-252497ed-38c0-4ef8-8fcb-623bb0d10cb6.png)

**Comment by fdevinc** [comment]
Hi @Bryanttt-tang, it is hard to understand the problem from here! If you come to today's tutorial, we will be happy to help you find a solution :)
