### ISSUE TITLE
CMake path problems

### ISSUE THREAD

**Issue by kilian-scheidecker** [CMM-22/a1#7]
Hello,
when I clone the repository from github I get direclty some error warnings. It has something to do with the CMake path. I don't know what is causing the problem but because of this I cannot build. These are the messages I get :
<img width="348" alt="warning1" src="https://user-images.githubusercontent.com/101058972/158614602-f36c3043-6e77-4d4b-84a7-0f9bd23c9ba9.PNG">
<img width="960" alt="warning2" src="https://user-images.githubusercontent.com/101058972/158614608-93876310-6e83-4e14-95ee-8c3a1376173d.PNG">

**Comment by fdevinc** [comment]
Hi @kilian-scheidecker, if you come to today's tutorial, we will be happy to help you with your issue :)
