### ISSUE TITLE
Strange indexing of ddendEffector_ddangles

### ISSUE THREAD

**Issue by yuhan-zh** [CMM-22/a1#8]
Hi,
      I found the indexing of the output of ddendEffector_ddangles() strange. The testing file requires the indexing of the 2*2*2 matrix to be: theta0/theta1, x/y, theta0/theta1. But, I think the indexing of the second derivative should be: x/y, theta0/theta1, theta0/theta1. And the latter one is actually more convenient to compute hessian.
      Is there any reason we are using the former one?

Best,
Yuhan

**Comment by fdevinc** [comment]
Hi @yuhan-zh, there is no special reason for our choice. Many different conventions exist, and we chose one that we found simple. As to the computation of the Hessian, the difference between conventions more or less boils down to a handful of matrix transpositions :)
